server:
  port: 8080

spring:
  application:
    name=: unit-test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: postgres
    password: admin
  h2:
    console:
      enable: true
      path: /h2-console